printWidth: 120
semi: false
singleQuote: true
jsxSingleQuote: true
trailingComma: "all"
useTabs: false
tabWidth: 2
bracketSpacing: true
bracketSameLine: false
arrowParens: "always"
endOfLine: "auto"
quoteProps: "as-needed"
plugins:
  - "@ianvs/prettier-plugin-sort-imports"
importOrderParserPlugins:
  - "typescript"
  - "jsx"
  - "decorators"
importOrder:
  - ^(react|react-router-dom)$
  - ""
  - <THIRD_PARTY_MODULES>
  - ""
  - ^(?!.*[.](css|scss|svg)$)[./].*$
  - ""
  - .(css|scss|svg)$
