services:
  caddy:
    ports:
      - "443:443"
      - "443:443/udp"
    environment:
      SERVER_HOST: https://${SERVER_DOMAIN}
      API_HOST: https://${API_DOMAIN}
      TLS_CERT_PATH: /certs/${TLS_CERT_FILE}
      TLS_KEY_PATH: /certs/${TLS_KEY_FILE}
      TLS_MODE: tls_on
    volumes:
      - $PWD/caddy/certs:/certs:ro
