services:
  caddy:
    environment:
      BACKEND_DOMAIN: backend
    volumes:
      - frontend_build:/srv
    depends_on:
      - backend
    # Default caddy command borrowed from https://github.com/caddyserver/caddy-docker/blob/master/Dockerfile.tmpl
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]

  frontend:
    build:
      context: frontend
      args:
        NODE_ENV: production
        SERVER_DOMAIN: ${SERVER_DOMAIN}
        MEDIA_HOSTING_URL: ${MEDIA_HOSTING_URL}
        API_DOMAIN: ${API_DOMAIN}
        VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
    restart: "no"
    volumes:
      - frontend_build:/frontend

  backend:
    build:
      context: backend
    restart: always
    environment:
      SITE_DOMAIN: ${SERVER_DOMAIN}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SENDING_BLUE_API_KEY: ${SENDING_BLUE_API_KEY}
      DEEPL_API_KEY: ${DEEPL_API_KEY}
      MEDIA_HOSTING_URL: ${MEDIA_HOSTING_URL}
      MEDIA_HOSTING_DIMS_AES_KEY: ${MEDIA_HOSTING_DIMS_AES_KEY}
      BARMALINI_USER_ID: ${BARMALINI_USER_ID}
      BARMALINI_KEY: ${BARMALINI_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ACCESS_TOKEN_TTL_SECONDS: ${ACCESS_TOKEN_TTL_SECONDS}
    depends_on:
      - mysql
      - redis
      - feed
      - elasticsearch-setup

  elasticsearch-indexer:
    depends_on:
      backend:
        condition: service_started # TODO change to service_healthy when we have a healthcheck


volumes:
  frontend_build:
