services:
  caddy:
    ports:
      - "443:443"
      - "443:443/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DEV: true
      SERVER_HOST: https://${SERVER_DOMAIN}
      API_HOST: https://${API_DOMAIN}
      TLS_CERT_PATH: /certs/${TLS_CERT_FILE}
      TLS_KEY_PATH: /certs/${TLS_KEY_FILE}
    volumes:
      - $PWD/caddy/on-tls.Caddyfile:/etc/caddy/working.tls.Caddyfile:ro
      - $PWD/caddy/certs:/certs:ro

  mysql:
    ports:
      - "3306:3306"
      - "33060:33060"

  redis:
    ports:
      - "6379:6379"

  feed:
    ports:
      - "6767:6767"
