version: '3.7'

services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      IMGUR_CLIENT_ID: ${IMGUR_CLIENT_ID}
    volumes:
      - $PWD/caddy/Caddyfile.ssl.dev:/etc/caddy/Caddyfile
      - $PWD/caddy/certs:/certs
      - caddy_data:/data
      - caddy_config:/config
    # Default caddy command borrowed from https://github.com/caddyserver/caddy-docker/blob/master/Dockerfile.tmpl
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile", "--watch"] 

  mysql:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_db:/var/lib/mysql
      - $PWD/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "3306:3306"
      - "33060:33060"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  caddy_data:
  caddy_config:
  mysql_db:
  redis_data:
