services:
  caddy:
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"


  mysql:
    ports:
      - "3306:3306"
      - "33060:33060"

  redis:
    ports:
      - "6379:6379"

  feed:
    ports:
      - "6767:6767"

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"

