version: '3.9'

services:
  mysql-test:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: orbitar
    volumes:
      - mysql_test_db:/var/lib/mysql
      - ../mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-porbitar"]
      interval: 5s
      timeout: 20s
      retries: 10

  redis-test:
    image: redis:7
    restart: always
    command: redis-server --save 20 1 --requirepass testpass
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data

  frontend-test:
    build:
      context: ../frontend
      args:
        NODE_ENV: production
        SERVER_DOMAIN: test.orbitar.local
        API_DOMAIN: api.test.orbitar.local
    restart: "no"
    volumes:
      - frontend_test_build:/frontend

  backend-test:
    build:
      context: ../backend
    environment:
      SITE_DOMAIN: test.orbitar.local
      NODE_ENV: test
      MYSQL_HOST: mysql-test
      MYSQL_PORT: 3306
      MYSQL_USER: orbitar
      MYSQL_PASSWORD: orbitar
      MYSQL_DATABASE: orbitar_db
      REDIS_HOST: redis-test
      REDIS_PORT: 6379
      REDIS_PASSWORD: testpass
      FEED_INDEX_HOST: feed-test
      FEED_INDEX_PORT: 6767
    ports:
      - "5001:5001"
    command: >
      sh -c "
        sleep 5 &&
        npm run migration:test wait-and-up &&
        npm run start:test
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "http://localhost:5001/api/v1/status"]
      interval: 5s
      timeout: 20s
      retries: 10
    depends_on:
      mysql-test:
        condition: service_healthy
      redis-test:
        condition: service_started
      feed-test:
        condition: service_started

  feed-test:
    build:
      context: ../feed
    ports:
      - "6768:6767"

  caddy-test:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      SERVER_DOMAIN: test.orbitar.local
      API_DOMAIN: api.test.orbitar.local
    volumes:
      - ../caddy/Caddyfile.test:/etc/caddy/Caddyfile:ro
      - frontend_test_build:/srv:ro
      - caddy_test_data:/data
      - caddy_test_config:/config
    depends_on:
      backend-test:
        condition: service_healthy
      frontend-test:
        condition: service_started

volumes:
  mysql_test_db:
  redis_test_data:
  frontend_test_build:
  caddy_test_data:
  caddy_test_config:
