name: build
on: [pull_request]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-backend-${{ hashFiles('./backend/package.json') }}
          restore-keys: npm-backend-
      - name: install_dependencies
        working-directory: "backend"
        run: npm install
      - name: run build
        working-directory: "backend"
        run: npm run build
      - name: test
        working-directory: "backend"
        run: npm run test

  build-frontend:
    runs-on: ubuntu-latest
    env:
      CI: '' # hack to allow build with warnings. FIXME: fix warnings are remove in the future
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-frontend-${{ hashFiles('./frontend/package.json') }}
          restore-keys: npm-frontend-
      - name: install_dependencies
        working-directory: "frontend"
        run: npm install
      - name: run build
        working-directory: "frontend"
        run: npm run build