name: Build Docker
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    paths:
      - .github/workflows/build-docker-dev.yml
      - compose.yml
      - compose-dev.yml
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            dc-file: [compose.yml, compose-dev.yml]
            tls: ["", "True"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker
        env:
          TLS_ENABLED: "${{ matrix.tls }}"
        run: docker compose -f ${{ matrix.dc-file }} build --no-cache

  validate-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate docker-compose.dev.yml
        run: docker compose -f docker-compose.dev.yml config

      - name: Validate docker-compose.ssl.dev.yml
        run: docker compose -f docker-compose.ssl.dev.yml config
