name: Validate Caddyfile
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    paths:
      - .github/workflows/build-caddy.yml
      - caddy/**/*
  workflow_dispatch:
        
jobs:
  validate-caddyfile:
    runs-on: ubuntu-latest
    container: caddy
    env:
      SERVER_DOMAIN: orbitar.test
      BACKEND_DOMAIN: orbitar.backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Caddyfile
        env:
          SERVER_HOST: http://orbitar.test
          API_HOST: http://api.orbitar.test    
        run: caddy validate --config caddy/Caddyfile
      - name: Enable TLS
        run: |
          cd caddy
          rm off.tls.Caddyfile
          mv on-tls.Caddyfile on.tls.Caddyfile
          openssl req -x509 -sha256 -nodes -newkey rsa:2048 -days 365 -config openssl.cnf -extensions req_ext -subj "/C=US/CN=orbitar.test" -keyout certs/orbitar.key -out certs/orbitar.crt
      - name: Validate Caddyfile with TLS
        env:
          SERVER_HOST: https://orbitar.test
          API_HOST: https://api.orbitar.test    
        run: caddy validate --config caddy/Caddyfile
      - name: Switch to deploy-frontend
        run: |
          rm caddy/dev.frontend.Caddyfile
          mv caddy/deploy-frontend.Caddyfile caddy/deploy.frontend.Caddyfile
      - name: Validate Caddyfile with deploy-frontend
        env:
          SERVER_HOST: https://orbitar.test
          API_HOST: https://api.orbitar.test    
        run: caddy validate --config caddy/Caddyfile

