name: Build Docker
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    paths:
      - .github/workflows/build-docker-dev.yml
      - _compose.base.yml
      - _compose.deploy.base.yml
      - _compose.deploy.nonssl.yml
      - _compose.deploy.ssl.yml
      - _compose.dev.nonssl.yml
      - _compose.dev.ssl.yml
      - compose-deploy-nonssl.yml
      - compose-deploy-ssl.yml
      - compose-dev-ssl.yml
      - compose.yml      
  workflow_dispatch:
        
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build backend, frontend & feed
        run: docker compose -f compose-deploy-nonssl.yml build --no-cache backend frontend feed

  validate-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate compose.yml
        run: docker compose config

      - name: Validate compose-dev-ssl.yml
        run: docker compose -f compose-dev-ssl.yml config

      - name: Validate compose-deploy-ssl.yml
        run: docker compose -f compose-deploy-ssl.yml config

      - name: Validate compose-deploy-nonssl.yml
        run: docker compose -f compose-deploy-nonssl.yml config
