name: Build Docker
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    paths:
      - .github/workflows/build-docker-dev.yml
      - docker-compose.yml
      - docker-compose.override.yml
      - docker-compose.dev.ssl.yml
      - docker-compose.deploy.yml
      - docker-compose.deploy.nonssl.yml
      - docker-compose.deploy.ssl.yml
  workflow_dispatch:
        
jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dc-file: [docker-compose.override.yml, docker-compose.deploy.yml]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build backend & frontend
        run: docker compose -f docker-compose.yml -f ${{ matrix.dc-file }} build --no-cache backend frontend feed

  validate-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate docker-compose
        run: docker compose config

      - name: Validate docker-compose.dev.ssl.yml
        run: docker compose -f docker-compose.yml -f docker-compose.dev.ssl.yml config

      - name: Validate docker-compose.deploy.yml with SSL
        run: docker compose -f docker-compose.yml -f docker-compose.deploy.yml -f docker-compose.deploy.ssl.yml config

      - name: Validate docker-compose.deploy.yml with NoSSL
        run: docker compose -f docker-compose.yml -f docker-compose.deploy.yml -f docker-compose.deploy.nonssl.yml config
