name: lint
on: [pull_request, push]

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-backend-${{ hashFiles('./backend/package.json') }}
          restore-keys: npm-backend-
      - name: install_dependencies
        working-directory: "backend"
        run: npm install
      - name: run linter
        working-directory: "backend"
        run: npm run lint

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-frontend-${{ hashFiles('./frontend/package.json') }}
          restore-keys: npm-frontend-
      - name: install_dependencies
        working-directory: "frontend"
        run: npm install
      - name: run linter
        working-directory: "frontend"
        run: npm run lint